### ISSUE TITLE
Tools aren't synced from Server to Client

### ISSUE THREAD

**Issue by wgaylord** [h3xcat/gmod-mappatcher#10]
If you define a new tool (make a new lua file that ends up in the tools directory) server side it will exist and be fine and also send the lua to the client, BUT you can't access this tool from the map patch menu since it uses a hard coded list. 

I think that the server should sync the list of available tools to the client when the editor is opened.

**Comment by h3xcat** [comment]
Done, you should be able to create new tools and make them visible by setting `TOOL.VisibleInMenu` to `true`. Use `TOOL.MenuPriority` to specify tool location in the menu.
