### ISSUE TITLE
Errors when in editor since update

### ISSUE THREAD

**Issue by ghost** [h3xcat/gmod-mappatcher#12]
Since the March 13 update being in the mappatcher editor seems to cause a large number of lua errors. From limited testing it still works however.

![Screenshot 2024-03-17 015533](https://github.com/h3xcat/gmod-mappatcher/assets/1758237/d67657d1-abe5-4f4d-88de-1e5f7a617c46)

**Comment by h3xcat** [comment]
I'm not able to reproduce it.

**Comment by ghost** [comment]
Looks like it may have been an issue with a specific map or a fluke - I can't reproduce it now either. Not a clue of what map I was on at the time.
Sorry for the false alarm.
