### ISSUE TITLE
Camera shake after teleportation [BUG]

### ISSUE THREAD

**Issue by Flapchik** [h3xcat/gmod-mappatcher#7]
https://user-images.githubusercontent.com/58729268/113876066-0d71aa00-97c0-11eb-9869-09bd64e55758.mov

https://user-images.githubusercontent.com/58729268/113876414-680b0600-97c0-11eb-9161-814621aec121.mov

**Comment by h3xcat** [comment]
It's a bug with the source engine, I'm not quite sure how I could fix it.
